// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9ud9_JmXV8dEVI8BvY00_tFbsVOif0LY',
    appId: '1:159707000564:web:dff4133b3e2fc3133d38a1',
    messagingSenderId: '159707000564',
    projectId: 'groceries-58dd0',
    authDomain: 'groceries-58dd0.firebaseapp.com',
    storageBucket: 'groceries-58dd0.firebasestorage.app',
    measurementId: 'G-F56TFQKR6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDspPHy58LGT_of6IlrpmMG1zbfLXR01ic',
    appId: '1:159707000564:android:e4dd7b22c69f53473d38a1',
    messagingSenderId: '159707000564',
    projectId: 'groceries-58dd0',
    storageBucket: 'groceries-58dd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpLVvLjQ5d1cHy1xpyGeoHBfomoZ8uMbE',
    appId: '1:159707000564:ios:1f5b9bd16ad6aa733d38a1',
    messagingSenderId: '159707000564',
    projectId: 'groceries-58dd0',
    storageBucket: 'groceries-58dd0.firebasestorage.app',
    iosBundleId: 'com.example.groceries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpLVvLjQ5d1cHy1xpyGeoHBfomoZ8uMbE',
    appId: '1:159707000564:ios:1f5b9bd16ad6aa733d38a1',
    messagingSenderId: '159707000564',
    projectId: 'groceries-58dd0',
    storageBucket: 'groceries-58dd0.firebasestorage.app',
    iosBundleId: 'com.example.groceries',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9ud9_JmXV8dEVI8BvY00_tFbsVOif0LY',
    appId: '1:159707000564:web:40a3eb1e32d384bd3d38a1',
    messagingSenderId: '159707000564',
    projectId: 'groceries-58dd0',
    authDomain: 'groceries-58dd0.firebaseapp.com',
    storageBucket: 'groceries-58dd0.firebasestorage.app',
    measurementId: 'G-9YHNT2X37S',
  );
}
